# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-15 19:35
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Annotation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=600)),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_path', models.CharField(max_length=500)),
                ('visual_genome_id', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='PoolItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_done', models.BooleanField(verbose_name=False)),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='annotation.Image')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='annotation',
            name='pool_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='annotation.PoolItem'),
        ),
    ]
